### ISSUE TITLE
Proposed processes for creating and updating a DIDDoc

### ISSUE THREAD

**Issue by swcurran** [bcgov/trustdidweb#11]
Here is a stab at the processes for creating an initial DIDDoc with all the features, and for updating a DIDDoc.

* Create the DIDDoc with the desired content, leaving placeholders for the DID identifier `{{SCID}}`. Include in the DIDDoc:
  * The DID identifier as the `id` and must include an instance of `{{SCID}}`
  * The top level `controller` that is self-referencing (same DID as `id`) or references an external controller.
    * If omitted, the `controller` is assumed to be the DID itself.
    * If the entry references multiple controllers **any** of the DIDs is authorized to update the DIDDoc.
  * Optional: `service` entries to be used to find referenced paths used by the DID (e.g., AnonCreds objects)
  * Optional: `service` entry with an `id` of `whois` that is of type LinkedVP
  * Any desired `alsoKnownAs`, with/without SCID
  * Any other content.
* Call a routine to generate the SCID
  * Process `scid = sha256(JCS(DIDDoc))` -- see #6 
* Update the DIDDoc with the SCID replacing the placeholder -- the result is the `versionID=0` DIDDoc
* Call a routine to generate the first log with the content, any necessary `parameters` (such as the version of the Spec being used) -- excluding the `proof`.
  * See #20
  * The `prevEntryHash` is null for the first entry. Subsequent entries use the `entryHash` from the previous log entry.
* Have a the `entryHash` signed as needed to create the `proof`, and add the `proof` item to the log entry.
  * The authorized keys for signing the `proof` are found from resolving the controller(s) listed in the initial DIDDoc. Subsequent entries use keys found from resolving the controller(s) listed in the initial DIDDoc
* Publish the log at the prescribed location according to the DID.
* Optional: Transform the initial (current) DIDDoc to a `did:web` by a text change of the `did:tdw` to `did:web`, and adding an `alsoKnownAs` entry for this DID and publish the resulting `did.json` file at the prescribed location.

Authorized signing keys to update the DIDDoc:

* Since the `controller` references DIDs and not specific keys in those DIDs, the method assumes the controller key for each controller DID is:
  * The `authentication` key type (if found), else the `verificationMethod` key type.
  * Nice to have: Support added for the use of the `verifiableCondition` as a reference from the `authentication` type or as an alternative to the `verificationMethod` in the DID.
* It is not clear to us that `authentication` is the right key type to use to demonstrate authorization to update a DIDDoc. For now, it is good enough based on the discussions we have had in the community, but we probably need to dig deeper into this.
* The controllers MUST be either:
  * The DID itself (key references are in the DIDDoc)
  * Other resolvable `did:tdw` or `did:web` DIDs
  * Copies in the DIDDoc of the relevant `verificationMethod`s for an external controller DID
* Otherwise, the DID resolution process returns an error `404 - NOT RESOLVABLE`

Generate the log entry for the DIDDoc update - see #20 

Update the DIDDoc:

* Update the DIDDoc as necessary. This could include updating the `authentication` keys if the DIDDoc contains such keys.
  * The `id` of the DIDDoc MAY be changed -- see moving the DIDDoc.
  * Anything else can be updated, although the items listed in the section above on creating the DIDDoc should be included.
* Call the routine (described above) to generate the next history log entry.
* Publish the updated log, accessible as required by the DID
* Optional: Generate and publish a `did:web` DIDDoc as described above.

Moving a DIDDoc:

* Permitted by changing the DID (effectively, creating a new DID, but with the previous DIDs history)
* Ideally a redirect is provided to the new DID, and the addition of an `alsoKnownAs` for the old DID.
  * If the old DID is resolved, and their is a Web Redirect to the new location, the resulting DIDDoc has the `id` of the old DID, and an `alsoKnownAs` for the new DID (or an `equivalentID`?).
* See #19

**Comment by swcurran** [comment]
Old version of the description of this issue that has been updated with our latest thinking. Keeping this just for the fun of it.

-----

Here is a stab at the processes for creating an initial DIDDoc with all the features, and for updating a DIDDoc.

* Creating a DID and DIDDoc
    * Determine the DID Controller — self-controlled, controlled by others?
    * Generate the DIDDoc items (e.g., `verificationMethod`, `authentication`, etc.) for each key to be published in the DIDDoc
    * Generate a pre-rotation key for each key, if wanted.
        * Make a copy of the DIDDoc key item (JSON).
        * Replace the current public key with the pre-rotation public key.
        * Add the `nextKey` item and make it a selfhash placeholder.
        * Run `selfhash` on the DIDDoc item copy.
        * Take the resulting `nextKey` from the copy and put it into the `nextKey` item of the actual DIDDoc key item.
    * Create the DIDDoc with the SCID placeholders.
        * Set the top level `controller` item.
        * Set the list of `alsoKnownAs` items, each with a SCID placeholder.
        * Leave out the `id` of the DID.
        * Set `versionID` to 0
        * Set `created` to `now()`
        * Set `updated` to `now()`
        * Set `prevProof` to an empty list `[]`
    * Run `selfhash` to generate the SCID and populate the placeholders.
* Sign the DIDDoc
    * Remove the DIDDoc must not have the `id` field in the DIDDoc.
    * Have one or more of the DID Controller keys create a `proof` across the DIDDoc.
    * Add the `proof` to the DIDDoc.
* Publish the DID
    * For each location the DID is to be published.
        * Add the `id` item into the DIDDoc if the item is to be statically placed into the DIDDoc.
        * Publish the DIDDoc
* Update a DIDDoc
    * Make a copy of the existing DIDDoc.
    * As needed, add a pre-rotation key to a DIDDoc key item, or rotate keys that have pre-rotation keys.
        * Update the key item to make the pre-rotation key (if needed).
        * Follow the same steps to generate a pre-rotation key and add it as the `nextKey` to the key item.
    * Add other content as appropriate.
    * Set the DIDDoc metadata:
        * Update (if necessary) the top level `controller` item.
        * Update (if necessary) the `alsoKnownAs` list, each with a SCID.
        * Remove (if necessary) the `id` of the DID.
        * Set `versionID` to the previous `versionID`+1
        * Leave `created` unchanged
        * Set `updated` to `now()`
        * Set `prevProof` to the `proof` and remove `proof`
* Sign the updated DIDDoc
    * Have one or more of the DID Controller keys from the previous DIDDoc create a `proof` across the DIDDoc.
    * Add the `proof` to the DIDDoc.
* Republish the DIDDoc
    * Same as with the initial publishing, accounting for any changes in the `alsoKnownAs` list.

**Comment by brianorwhatever** [comment]
This has been well documented in the spec now
