### ISSUE TITLE
How to do prerotation

### ISSUE THREAD

**Issue by brianorwhatever** [bcgov/trustdidweb#5]
Which keys are prerotated? Is it just the controller keys or is this a requirement of every verification method?

and How do we define prerotation?

**Comment by andrewwhitehead** [comment]
I think that if we want to support prerotation in this DID method, then it should be supported (opt-in) for all verificationMethod entries where they key type can support it. I suspect this would require new verification methods, though, like 'Multikey2024'. It seems like after such a key rotation, the same ID and verification method would have to be used in the new key definition?

In the case of external controllers, key rotation/prerotation must be handled within their DID documents, according to their DID methods: that would be outside of scope (although they may also be using this DID method).

**Comment by swcurran** [comment]
After thinking about it for a while, here is what I came up with.

* Pre-rotation is optional for **_any_** identified public key published in a DIDDoc.
    * Identified meaning that the “id” value is the same in subsequent versions of the DIDDoc, but the associated public key can change (which is the definition of key rotation).
    * Pre-rotation is a general extension to the DID Core specification, and is not specific to the controller DID or keys.
* An item `nextKey` in a key structure (e.g., `verificationMethod`, `authentication`, `keyAgreement`, etc.) is the hash of the public multikey or JWK (canonicalization?) of the next public key to be published.
    * Or perhaps of the entire key structure, excluding the `nextKey`?
    * Or perhaps the self hash of the entire key structure?
* To verify a key rotation in a DIDDoc that uses pre-rotation:
    * Get the previous version of the DIDDoc
    * Determine if, for any identified public key, the public key has been changed.
    * For each:
        * Determine if there is a `newKey` for the changed key in the previous DIDDoc.
        * Verify that the hash of the data containing the new public key equals the `nextKey` value from the previous version of the DIDDoc.

**Comment by swcurran** [comment]
We can provide an implementers guide for why one would use this and how, covering the use cases we discussed yesterday:

- having two keys in one location
- having the active key in one location and the next key in another (e.g. Azure and AWS)
- moving to a PQ key

For the latter two scenarios, the approach is to update the DIDDoc twice to make the first manageable (mininimally use the “other” environment).

**Comment by brianorwhatever** [comment]
I'm not sure I agree that all of the verification methods should be pre-rotatable. The core reason of including the pre-rotation is to ensure someone who gains access to your current keys can't rotate the DID away from your authority. I don't think there is any reason to include it for keys that aren't used for authorizing changes to the DID state -- In other words this is a security feature for the DID method not for verification methods generally. So if you have the pre-rotation requirement on the document state you shouldn't need to worry about the items in the document itself. The added complexity of managing those next keys should be limited as much as possible imo. This is part of the reason I like the separation of concerns used by `did:plc` with their `recoveryKeys` as mentioned in #3.

**Comment by andrewwhitehead** [comment]
@brianorwhatever One other circumstance I was considering: in the case where verifiable conditions is used, the document might contain keys copied from a controller's DID documents (or at least referenced there, including the key ID). In order to preserve the ability for that specific key ID to be used in authorizing updates, the controller would need to rotate it 'in place' – although not necessarily using pre-rotation with a commitment to a specific key.

I think we might want to consider a `verificationMethod` property like `rotation` with optional sub-properties like `nextKey` and `versionId`.

**Comment by swcurran** [comment]
While we want it to retain control over the DIDDoc, I don’t see a need to limit the feature to just those keys — especially since it is (seemingly) difficult to determine what are the keys that are authorized to update a DIDDoc. The pre-rotation key commitment must be beside the public key it will replace, so it can’t be in an item that is just the reference to the key (e.g., an `authentication` item that references a `verificationMethod`).

**Comment by swcurran** [comment]
Proposed (excellent!!) solution from @brianorwhatever.  The first item in the list is an addition from me.

* A `parameters` flag (`"prerotation" : "true"`) indicates that keys subsequently added to the DIDDoc must have a prerotation entry in the DID log.
  * The flag defaults to `false`.
  * Once set to `true` the flag cannot be changed to `false`.
* A `parameters` entry `"preKeys" : { "<hash>" }` is a set of hashes of DIDDoc key items that can be added to the DIDDoc.
  * Hashes are calculated using the "normal" `did:tdw` hashing algorithm across the DID key entry item (e.g., `verificationMethod`, etc.).
  * DID key entries that are only a reference to another key in the DIDDoc are not included in the prerotation handling -- e.g. that only have an `"id": "#<ref>"`
*  A resolver processing a DID log must verify that all key items subject to prerotation exist in the set of `preKeys` hashes.

**Comment by swcurran** [comment]
@brianorwhatever did I get it right?  The need for an handling of the flag seems necessary to me, but turning it off after it has been used seemed to defeat the purpose.  Also not sure if the enforcement of the "not needed on keys that reference other keys" is possible, even if it useful.  What do you think?

**Comment by swcurran** [comment]
Resolved, with the technique documented in the spec. and implementations mostly there, but needing a couple of tweaks to align with the latest revision.
