### ISSUE TITLE
Keeping the SCID independent of the HTTPS URL

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/trustdidweb#74]
Using ONLY the proposed syntax `did:tdw:{SCID}:domain:path`, and not allowing for the SCID to occur in the HTTPS URL simplifies the spec significantly and would be beneficial for security in removing any ambiguity.

If the SCID is allowed to be case-sensitive (which it cannot be in a subdomain), then we could also use base58 for the encoding and potentially reduce the minimum length of the SCID at the same security level for second preimage attacks.

While `did:tdw:{SCID}.domain.example` or `did:tdw:domain.example:{SCID}` looks nice and readable, it would also allow for `did:tdw:{SCID1}.domain.example:{SCID2}` or `did:tdw:domain.example:{SCID1}:{SCID2}` meaning that either SCID could be the one defined by the log file.

**Comment by swcurran** [comment]
@brianorwhatever , @dmitrizagidulin — do you agree? 

My leaning, having written and explained the spec, is that this is the right thing to do. A SCID as a subdomain is kinda silly and unlikely.  A SCID as file path is a bit more reasonable, but there are lots of things that can be done here.

If we do switch to base58 we would eliminate the option of putting in the SCID twice in the DID and so that it appears once in the HTTPS URL, e.g. `did:tdw:{SCID}:example.com:dids:{SCID}`

So my thought is to go with what is proposed.

**Comment by andrewwhitehead** [comment]
Base58 for a subdomain or path component (or query parameter or whatever) is actually fine, it only becomes a problem when we rely on it for security. If the DID was `did:tdw:{SCID}.domain.example` then any different capitalization of the SCID would be considered equivalent because domain names are case insensitive. You could end up resolving a different subdomain, with a different log file and a slightly different SCID (although achieving that hash collision would still be difficult, you would have many more options).

If the SCID is enforced separately from the URL then I don't think there is an issue, although we might still want to recommend against using it as a subdomain to avoid ambiguity. The DID Core spec does say that case sensitivity within the method-specific ID is up to the DID method.

**Comment by swcurran** [comment]
To summarize, the changes to be made are:

- SCID is required in the first element of the method-specific identifier `did:tdw:<scid>:<did web method specific identifier>`
- If the SCID is only in the required location in the DID, it will not be in the HTTPS address.
- SCID MAY be placed in the method-specific identifier in the domain or path elements of the `<did web method specific identifier>`
  - In that case, it will appear multiple times in the DID
  - it is a bad idea to put it in the subdomain for reasons Andrew stated above.
- The SCID algorithm changes to: `left(base58(hash(JCS(preliminary log entry with placeholders))), <length 28+>)`
   - Should the length be reduced from 28, and if so, to what?
- The SCID is case-sensitive
- The ABNF for SCID changes to Base58 characters.

**Comment by andrewwhitehead** [comment]
In base58, the SCID can be shortened to 24 characters while maintaining the same number of encoded bits: `log2(32**28) = 140; log2(58**24) = 140.6`.

For interest sake, it would be the same minimum length if we used base64-URL. And that can include underscores, which might not play nicely with subdomains if somebody were to use them there.

**Comment by dmitrizagidulin** [comment]
The changes proposed by @swcurran above all seem ok. +1 from me. (No opinion on whether to shorten the length from 28).

**Comment by swcurran** [comment]
Creating the PR now.  I'm going to leave the SCID now, so as to avoid the potential confusion/difference when the SCID is inserted by the DID controller as the subdomain, as specified by @andrewwhitehead above ([comment](https://github.com/bcgov/trustdidweb/issues/74#issuecomment-2237090692)].

It is an edge case either way, but I'm leaning towards forgoing the 4 character savings in the SCID for the subtle issues that could arise from changing it.

Please comment here or on the PR if I'm out to lunch on that...

**Comment by swcurran** [comment]
Addressed via #77
