### ISSUE TITLE
SHA-512/256 as the default hash

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/trustdidweb#75]
Unfortunately after 9 years it appears that sha3 is not generally available on web platforms. Using sha-512/256 (a 64 byte hash truncated to 32) would provide the same preimage resistance as sha3-256: https://csrc.nist.gov/projects/hash-functions#security-strengths

**Comment by swcurran** [comment]
Clarifying:

- the name of the hash algorithm is `sha-512/256`
- there is adequate implementations of the algorithm that it will not be a roadblock for implementers?

Thanks!

**Comment by andrewwhitehead** [comment]
sha-512 appears to be available on all major browsers which was the main stumbling block: `await window.crypto.subtle.digest("sha-512", Uint8Array.from("hello"))`. The truncation would be done afterward.

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#browser_compatibility

**Comment by brianorwhatever** [comment]
The table linked to above doesn't convince me of enough benefit.. I'd prefer to stick to the classic sha-256 everyone knows and loves. It is also already being used in data integrity proofs within this spec. If this works in web browsers though I am happy to switch.

**Comment by swcurran** [comment]
So we are going to go with `sha-256`. I’ll confirm/update the spec.

**Comment by brianorwhatever** [comment]
Yeah that is right sha-256. I think it’s right in the spec but the examples
need updating

**Comment by andrewwhitehead** [comment]
I agree we can't truncate the hash without losing bits of collision resistance (particularly preimage resistance), and we would likely want to maintain 128 bits as a minimum level. A sample DID using base32 might look like:
`did:tdw:wren2gpeqzh7kdlx3iq7yxkfjtd6cf5iqoqk3ve6xcy3ebd5impq:domain.example:path`

And using base58:
`did:tdw:5qaMSu6MJSe36DNTBqjdH6sCKKwNbgHTqvyG4BJJGRpA:domain.example:path`

I suppose for use in the resource URL (not in the leading SCID) we could support something like `{SCID:20}` to insert truncated versions, but I would probably leave that for a later version if at all.

**Comment by swcurran** [comment]
Are you saying it is necessary to increase from 28 to 52 characters if we stay with base32, or to 44 characters if we use base58?

Either way, we have to expand from the 28 we are using now?

**Comment by andrewwhitehead** [comment]
> Are you saying it is necessary to increase from 28 to 52 characters if we stay with base32, or to 44 characters if we use base58?
> 
> Either way, we have to expand from the 28 we are using now?

Yes that's the main thrust. Any shortening of the hash will likely make it too easy to concoct a new genesis transaction with the same SCID.

**Comment by swcurran** [comment]
Wow…that’s unexpected. I thought that was why we went from 24 to 28 characters in the SCID early on.

Can someone propose the definitive SCID algorithm we should use and I can update the spec (or put a PR into the spec :-) ).   Decisions on hash algorithm, encoding algorithm and length are needed.

**Comment by bj-ms** [comment]
I created a proposition as a PR: https://github.com/bcgov/trustdidweb/pull/79
