### ISSUE TITLE
How do we support the “whois” Verifiable Presentation functionality?

### ISSUE THREAD

**Issue by swcurran** [bcgov/trustdidweb#9]
For other web-based DID methods, we proposed that the DID URL `<did>/whois` would resolve to a VP containing VCs for which the DID is the `credentialSubject.id`, and the VP proof is from the DID.

How do we do that for this DID method?

Obviously, one option is to do exactly what is proposed above.

Another possibility is “linked-vp”. Need to add a reference for that.

**Comment by brianorwhatever** [comment]
[This](https://github.com/bcgov/didwebnext/pull/18/files#diff-530041f57612d4198a307f3c9593bd43824b8dcac73b9928d92b2793f5c0a7c4R39-R45) is what a a `LinkedVerifiablePresentation` would look like that can accomplish this goal. It has a `serviceEndpoint` in it that is a direct URL to get the VP. The `#whois` could simply be a convention recommended by this method
